### ISSUE TITLE
More highlighted proteins than expected

### ISSUE THREAD

**Issue by pidupuis** [PPiMapBuilder/PPiMapBuilder#41]
Sometimes there are more highlighted proteins than POIs.

**Comment by gcornut** [comment]
This bug is due to the UniProtEntrySet.contains method which not strict enough.

When requesting an interaction network with P08107 in human, the P48741 protein show up as a POI. P48741 and P08107 share the secondary accession P19790 whose entry have been demerged into those two proteins (http://www.uniprot.org/uniprot/P19790).
UniProtEntrySet.contains finds P48741 in the protein of interest pool using the P19790 identifier but it shouldn't.

The search of protein in a protein pool using secondary accession should return multiple results (If P19790 has an interaction, both P48741 and P08107 would need to be linked to its interactor). But, when searching if a protein is in the protein of interest pool, the search need to be done only using the primary accession of this protein.

**Comment by gcornut** [comment]
Fixed in 9056749
