### ISSUE TITLE
GO group term label

### ISSUE THREAD

**Issue by pabloech** [PPiMapBuilder/PPiMapBuilder#53]
could be possible that the attribute GO_slim_group_term gives a label to the visually formed group on the network panel? like this the user when export an image of the generated network (after PMB layout) already indicate the names of the functional groups.
I cannot find a way to map that label, the structure of cytoscape seems to only allow to map nodes and edges.
any Ideas?

**Comment by pabloech** [comment]
in the past the plugin Cerebral (http://www.pathogenomics.ca/cerebral/) had something similar to what I'm asking. They generated new networks with an independent layout and splitting the nodes vertically in layers (each layer can have a label-name-)

**Comment by pidupuis** [comment]
Display a label directly on the network background would require to have access to Cytoscape at a lower level because this is not a feature provided by the API. This would be really difficult and we don't know how to do it for now. Also, the label would be fixed.

A simpler solution would be to add a color by cluster and a legend as nodes using this same set of colors. See the following example:

![Example](http://img15.hostingpics.net/pics/320458networklegend.png)

In my example, the POI color is overrided but this is not necessary. I don't know if this is a problem but this solution would break the node number of the network.

**Comment by pabloech** [comment]
it seems a good approach. I like it. We should try. is this new legend node will appear already, before performing PMB layout or only after ?

**Comment by pidupuis** [comment]
Only after PMB layout

**Comment by pidupuis** [comment]
Done in v0.12.
The PMB visual style is not changed. A new visual style is created for each GO slim used.

Concretely, when you generate a network using PPiMapBuilder, a visual style called _"PPiMapBuilder Visual Style"_ will be created. Then, when you apply the PMB layout using for instance the **"Default Go Slim"**, a visual style called **"PMB_Default_Go_Slim"** will be created based on _"PPiMapBuilder Visual Style"_ with a color mapping on cluster value. You can easily switch between the visual styles (for example returning to _"PPiMapBuilder Visual Style"_ allows you to see the _queried proteins_ easily).
