### ISSUE TITLE
snapshot V0.12

### ISSUE THREAD

**Issue by pabloech** [PPiMapBuilder/PPiMapBuilder#64]
I’m testing the v012 but using Q16543 as POI the retrieval gets stuck in Fetch orthologs interactions in other organisms
if I only look in human I’ve got a network with blue nodes (with label) and red nodes (no label). Then If I explore the visual style and I click on Label..everything gets to back to normal, all labelled and nodes blue, except the yellow of the query.
The PMB worked beautifully :)

**Comment by pidupuis** [comment]
Have you loaded the ortholog cache in the settings panel ?
How long did you wait for the network to be created ? It seems that this POI network simply needs time to be generated...

We keep investigating

**Comment by pabloech** [comment]
Yes I think that since I installed an updated version of cytoscape then I forgot to load the ortholog cache. Now I tested P49407 & P32120, it worked nicely in good time but the second query doesn't appeared as query and colored as yellow because is false in Queried column.

**Comment by pabloech** [comment]
after doing the first query with P49407 & P32120 I tried the PMB using generic slim, not nice result with that one so I re-tried the PMB with the default GO slim..didn't work.I started a new session and re-tried the query with same guys. The output was not good in terms of colors (all red nodes) but then I did the PMB with default slim GO and it was perfect with colors and all different functions (this query is a nice example how our pluging works!) It seems that there're problems when re running the plugin mutiple times in one session

**Comment by gcornut** [comment]
It seems that P32120 doesn't show as queried because it come from Bos taurus and PMB doesn't seem to find the human ortholog. I manually searched and found this protein in both the Inparanoid orthoXML repository (from which the cache is loaded) and the Inparanoid web service (used in absence of local cache).
Since that Bos taurus is not in your local cache, PMB fetches its ortholog via the Inparanoid webservice. But, it seems that PMB ignores organism that haven't been added to the user preferred list of organism.
So that's really a bug and I fixed it directly in the [v0.12 release](https://github.com/PPiMapBuilder/PPiMapBuilder/releases/tag/v0.12).

For the GO slim cluster layout, it's seems you often encounter this bug (#48). We have yet to discover how to reproduce it reliably :/.

**Comment by pidupuis** [comment]
It seems that there are in fact several distinct layout bugs:
- **Layout empty** which occurs rarely and for now without identified reasons #48
- **Apply a layout several times** on the same network fails during the GO slim fetching. This is the bug you talk about in https://github.com/PPiMapBuilder/PPiMapBuilder/issues/64#issuecomment-107246924.
  
  So, when you apply several times the layout using the **same** GO slim, you have no problem because the GO have already been fetched the first time. However, when you apply the layout with **different** GO slim, the second time the GO are not fetched and you see no results. This is a bug which would imply to empty the GO columns before fetching the GO the second time #66
- **Red nodes in visual style**. I have never encountered this one and don't understand where the red color comes from. We need to find how to reproduce it.
