### ISSUE TITLE
URGENT! Unable to load PSICQUIC databases

### ISSUE THREAD

**Issue by pabloech** [PPiMapBuilder/PPiMapBuilder#69]
I can't make the plugin work!
it gives that message when try to do query or open settings
it happens the same on your computers or it's only mine?

**Comment by pabloech** [comment]
ok, here the answer:
http://www.ebi.ac.uk/Tools/webservices/psicquic/view/main.xhtml
I hope gets back
I need to do the demo tomorrow!

**Comment by pidupuis** [comment]
I saw it yesterday evening so I contacted the support team as fast as I saw it. They did not respond me yet...

This is still unavailable now...

**Comment by pidupuis** [comment]
I'm truly sorry but if Psicquic server is down, there is no way for our app to work since we use it to retrieve the interactions.

It's a nightmare that this happens just before your presentation...

**Comment by pidupuis** [comment]
I have a response from the support team. They will restart the servers "as soon as possible this morning". I hope this will be enough for you...

**Comment by pabloech** [comment]
yes, the answer the same to me
I hope is solved soon before 13 hs
anyway, at least I can work off-line with some trials that I saved. PPiMapBuilder still works in terms to recognise all the metadata like uniprot link to the protein information or the pubmed ID of the interaction..it's important to show that

**Comment by pidupuis** [comment]
Yes, if you have already generated networks (with datatable fullfilled), you'll be able to use the result panel. Also, since Psicquic is only used to retrieve the interactions, you'll be able to apply the PMB layout on a network you saved.
You can also present the settings query (a lot of organism available, cache system, ... only the database tab will be empty).

We are aware that the app depends a lot on Psicquic registry and we already planned to find a solution to be less dependent (see #24). But EBI servers are pretty reliables and it is really bad luck that it happens today...

**Comment by pidupuis** [comment]
Servers are back

**Comment by pabloech** [comment]
:)

**Comment by pabloech** [comment]
presentation and demo were a success!!
thanks for everything! later I'll come with issues and ideas

**Comment by pidupuis** [comment]
Great! :)
